### ISSUE TITLE
HMS Notification Message type

### ISSUE THREAD

**Issue by janbolat** [HMS-Core/hms-push-clientdemo-android#1]
Hi,
is there a way to get (read) the title and body of the message if the type is Notification Message (not Data Message)?

https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/push-introduction#h1-1576132561387

**Comment by HMSPushKit** [comment]
@janbolat
We support RemoteMessage.Notification.getTitle() methods to get the title of the Notification messages. You can find this information by [this documation](https://developer.huawei.com/consumer/en/doc/development/HMS-References/push-Notification-cls#getTitle) in detail. GetBody methods is similar to getTitle.
I hope this can help you.

**Comment by janbolat** [comment]
@HMSPushKit @Mike-mei 

I mean that if you send a message from a web console as a Notification Message (not Data Message), `onMessageReceived` won't be called (triggered). I tried both cases when the app is in foreground and background. 

![image](https://user-images.githubusercontent.com/6511056/89502846-71823f80-d7e7-11ea-9f88-482aacc8d3c1.png)

**Comment by HMSPushKit** [comment]
Sorry for that, we cannot get any notification information from the web console cause the notification is sent to Huawei Notification Center for Safety. But you can do this to get it. 

Send data messages , make your app in foreground and set foreground_show to false. This can make data messages to notification messages. And try RemoteMessage.Notification.getTitle() to get information.

Look at [this](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/android-fgrd-show-0000001050040126-V5).

**Comment by janbolat** [comment]
Thank you
