### ISSUE TITLE
为什么收不到离线推送消息？

### ISSUE THREAD

**Issue by dabaipj** [HMS-Core/hms-push-clientdemo-android#12]
在线可以收到消息，但app退出后，就收不到了，为什么？

**Comment by Mike-mei** [comment]
需要确认以下两点：
1. 是通过三方接入的还是直接接入的华为push服务。
2. 推送的是通知栏消息还是透传消息。

**Comment by dabaipj** [comment]
我就是用这个仓库项目，直接运行的，是直接接入的，默认应该是通知栏消息吧

**Comment by Mike-mei** [comment]
在线和App退出后推送的请求返回各提供一个

**Comment by dabaipj** [comment]
只看到获取token的log，推送的请求返回log怎么查看？
I/HMSSDK_HmsInstanceId: receive a token, refresh the local token
I/PushDemoLog: get token:IQAAAACy0nAmAACsz641vWYb4WMFYTLo3nO02-keyTLK1RiSogAYrcaaxWNrHBcV_nCzDWGrRZn3EWPcUrnl6Zj5vosCMc36q4DqtbqQPfqPPj5QwQ
I/PushDemoLog: sending token to server. token:IQAAAACy0nAmAACsz641vWYb4WMFYTLo3nO02-keyTLK1RiSogAYrcaaxWNrHBcV_nCzDWGrRZn3EWPcUrnl6Zj5vosCMc36q4DqtbqQPfqPPj5QwQ
I/HMSSDK_ReportAaidToken: The data storage region is empty.

**Comment by Mike-mei** [comment]
推送是一个request请求，请求成功了会有个response，要这个response

**Comment by dabaipj** [comment]
不明白，推送请求不是在华为的应用后台发出的吗？我在本地的logcat里只找到这种：
D/HMSPushLog60100302: [D/PushKit/HMSPushLog60100302 10577:12868 null:2] enter handleMessageResponse
2021-10-18 17:17:46.631 10577-10761/? I/HMSPushLog60100302: [I/PushKit/HMSPushLog60100302 10577:12868 null:105] msgType:2 [0:PassBy msg, 1:System notification, 2:normal notification, 3:HCM PassBy msg],userId:0

**Comment by dabaipj** [comment]
华为不会是不支持离线吧，我看官方文档，受限说明里写到：
终端设备是否在线。
如果设备离线，推送服务会缓存消息，待用户上线后，再将消息投递给用户。

我重新打开app后，确实会收到消息!-_-

**Comment by Mike-mei** [comment]
`token：IQAAAACy0nAmAACsz641vWYb4WMFYTLo3nO02-keyTLK1RiSogAYrcaaxWNrHBcV_nCzDWGrRZn3EWPcUrnl6Zj5vosCMc36q4DqtbqQPfqPPj5QwQ`
这个token查了是推送成功的。
描述在线可以收到消息，但app退出后，就收不到了。华为push是不会出现这种情况的，华为push通知栏消息本身就是离线消息，如果app运行时能收到消息，那app退出后也一定是能收到消息的。
要排查具体原因，还是需要提供请求的response，里面有requestid，用于查找记录。
下发消息的请求，请看官网：
https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/android-server-dev-0000001050040110
该请求如果成功会返回如下这种response：
```
{
    "code": "80000000",
    "msg": "Success",
    "requestId": "163455051624764928015301"
}
```

**Comment by dabaipj** [comment]
我是用官方的应用后台发送的推送通知的，你的意思，我要自己部署服务器去发送推送吗？

**Comment by dabaipj** [comment]
我等了四十分钟左右，终于看到推送消息了，跟华为官方的 智能客服 里的一个问题一样：
接入push，设备离线时，消息推送会有延迟，大约延迟在40分钟以上

**Comment by dabaipj** [comment]
这个延迟也太高了吧，有办法解决吗？

**Comment by Mike-mei** [comment]
这是跨区域推送消息，涉及大区消息前转，本身时延就很高，属于正常情况。尽量避免跨区域推送消息。

**Comment by dabaipj** [comment]
你之前不是说：华为push通知栏消息本身就是离线消息
但从这个表现来看，华为push还是会判断设备是否在线，在线则马上推送，离线则延后推送，是这样的吗？

**Comment by Mike-mei** [comment]
设备当然要在线才能收到消息，应用有没有启动不影响消息的推送。

**Comment by dabaipj** [comment]
我指的就是应用，在线则马上推送，离线则延后推送
