### ISSUE TITLE
使用服务器Jenkins打包卡在app:processReleaseAGCPlugin

### ISSUE THREAD

**Issue by IurKwan** [HMS-Core/hms-push-clientdemo-android#13]
持续集成下卡在app:processReleaseAGCPlugin这一步，电脑上是完全正常的

**Comment by Mike-mei** [comment]
打包卡在app:processReleaseAGCPlugin，请确认是否产生错误，请提供详细信息。此外，该项目请使用Android Studio进行打开或者编译，详细步骤请参考链接Readme

**Comment by IurKwan** [comment]
没有产生错误，一直运行此task，本地编译瞬间完成并且打包成功的

**Comment by Mike-mei** [comment]
建议使用Android Studio运行和编译，按照Readme指导进行操作就不会出问题的

**Comment by IurKwan** [comment]
好的，谢谢😁
