### ISSUE TITLE
emmm 想问下 华为push在其他厂商效果怎么样呢,会不会关闭app就收不到了

### ISSUE THREAD

**Issue by zhangruiyu** [HMS-Core/hms-push-clientdemo-android#2]
emmm 想问下 华为push在其他厂商效果怎么样呢,会不会关闭app就收不到了

**Comment by HMSPushKit** [comment]
您好，是这样的，华为推送能力依赖HMS Core（APK），用户可到华为应用市场下载安装该APK，如果不安装则不支持华为推送能力。即使安装了HMS Core（APK），推送能力也会受到系统限制，可能会影响消息推送的到达率。

**Comment by zhangruiyu** [comment]
嗯,其实作为开发者,还希望能把其他厂商的一起集成下,我想如果这样的话,肯定能增加华为推送的使用率,虽然集成其他厂商的通道不是华为应该干的,但是如果华为给大家的都搞了,那么反响肯定好到爆炸

**Comment by HMSPushKit** [comment]
是的呢，目前我们正在做这个需求，集成厂商的通道，预计今年第四季度上线，这样开发者就减少工作量了。

**Comment by zhangruiyu** [comment]
哇,太棒了

**Comment by zhangruiyu** [comment]
> 是的呢，目前我们正在做这个需求，集成厂商的通道，预计今年第四季度上线，这样开发者就减少工作量了。

你好哇 现在进度是什么样呢 新项目想切入到华为的来 然后其他厂商目前是个什么情况呢

**Comment by HMSPushKit** [comment]
> > 是的呢，目前我们正在做这个需求，集成厂商的通道，预计今年第四季度上线，这样开发者就减少工作量了。
> 
> 你好哇 现在进度是什么样呢 新项目想切入到华为的来 然后其他厂商目前是个什么情况呢

您好，目前我们开放的厂商通道有[iOS](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/ios-dev-progress-0000001062221191)和[FCM](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/3rd-party-push-integration-0000001050992231)，其他厂商暂时不支持。
