### ISSUE TITLE
Get Token and Delete Token return ApiException

### ISSUE THREAD

**Issue by EvgenyTerebenin** [HMS-Core/hms-push-clientdemo-android#6]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/17678440/98788701-580a1880-2412-11eb-9f7b-2596aad6ccda.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/17678440/98788728-5dfff980-2412-11eb-90ff-3e513a2a5bcd.png">

<img width="983" alt="image" src="https://user-images.githubusercontent.com/17678440/98789052-c8189e80-2412-11eb-90b1-79920b0926b6.png">
<img width="966" alt="image" src="https://user-images.githubusercontent.com/17678440/98789072-d1097000-2412-11eb-9d06-db535520434f.png">

**Comment by HMSPushKit** [comment]
Could you add more description in detail?

**Comment by EvgenyTerebenin** [comment]
> Could you add more description in detail?

Do you see my screenshots? I attached 4 images.
`String appId = AGConnectServicesConfig.fromContext(MainActivity.this).getString("client/app_id");` returns null
So that
`HmsInstanceId.getInstance(MainActivity.this).getToken(appId, "HCM");` 
throws ApiException with value 
`com.huawei.hms.common.ApiException: 907135000: arguments invalid`

Device: Huawei DUA-LX9, android 10, Magic UI 3.1.0, build 3.1.0.138(C10E3R2P2)

**Comment by HMSPushKit** [comment]
please make sure that :
1.Sign in to AppGallery Connect, download the agconnect-services.json file of your app, and copy the file to your app's root directory of the sample project.

2.Open the build.gradle file in the sample project, and change the value of applicationId to your app package name.
