### ISSUE TITLE
Is parameter “foreground_show” in notification message ignored?

### ISSUE THREAD

**Issue by vvche69** [HMS-Core/hms-push-clientdemo-android#7]
Hi!

I have a problem with notifcation messages handling in Xamarin app.

I've created a message service that implements HmsMessageService class, then have overridden its OnMessageReceived(RemoteMessage message) method.

My app succesfully obtains access tokens from server, receives data messages when in foreground, my device receives notification messages when app killed or in background and then starts an app on user tap, but I still can't intercept notification messages when app is in foreground. Notification is shown in NC on device but OnMessageReceived is never called.

The structure of my messages is almost the same as in officail docs:

`{
"message": {
    "notification": {
        "title": "message title",
        "body": "message body"
    },
    "android": {
        "notification": {
            "foreground_show": false,
            "click_action": {
                "type": 1,
                "action": "com.huawei.codelabpush.intent.action.test"
            }
        }
    },
    "token": [
        "pushtoken1"
    ]
}`

I've  got these recommended settings in AndroidManifest.xml:

`  <meta-data
            android:name="push_kit_auto_init_enabled"
            android:value="true"/>
        <service
            android:name=".MyHmsMessageService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.huawei.push.action.MESSAGING_EVENT"/>
            </intent-filter>
       </service>
`

Maybe I missed some parameters?

**Comment by Mike-mei** [comment]
You have to implement "IHmsPushEvent" interface to your Activity or you cannot listen events. This interfaces's functions provides the listening HmsPush events. 
**Solution:**
1)Implement "IHmsPushEvent" interface to Activity. 
2)Configure OnMessageReceived method.
3)Remote Message will be received, after he sends the notification.
4)Use GetNotification method to get notification data.

**Sample Code:**
```
public void OnMessageReceived(RemoteMessage message)
        {
            string MethodName = MethodBase.GetCurrentMethod().Name;
            RemoteMessage.Notification notification = message.GetNotification();
            Log.Info(MethodName,$"Title: {notification.Title}\nBody:{notification.Body}");
        }
```

For more details, see [docs](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/hmspushevent-0000001055880201-V1).

**Comment by vvche69** [comment]
I've found the real reason :)

I forgot to delete sample modules from xamarin-push-package-5.0.2.300 source files before compiling  Xamarin Android libraries. And  XamarinHmsPushDemo.Hmssample class intercepted my messages :)

Mea culpa, mea maxima culpa :)


But thank you anyway, your answer helped me to dive into Push Kit modules deeper :)
