### ISSUE TITLE
请问我如何监听用户点击通知的事件，或者如何监听通知到达？

### ISSUE THREAD

**Issue by ChuiXueShen** [HMS-Core/hms-push-clientdemo-android#8]
请问我如何监听用户点击通知的事件，或者如何监听通知到达？

**Comment by ChuiXueShen** [comment]
非透传消息好像没办法监听

**Comment by HMSPushKit** [comment]
您好，通知栏消息可以转透传消息进行监听，可以参照如下[指导](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/android-basic-receivemsg-0000001087370610)。
